version: "2"
linters:
    default: standard
    enable:
        - goconst
        - lll
        - gocritic
        - godoclint
        - prealloc
        - protogetter
        - reassign
        - testifylint
    settings:
        godoclint:
          default: all

issues:
    # Apply the fixes detected by the linters and formatters (if it's supported by the linter).
    # Default: false
    fix: true

# Options for analysis running.
run:
    # Include test files or not.
    # Default: true
    tests: false
