# https://taskfile.dev

version: "3"

tasks:
  test:
    cmds:
      - go test ./...
  build-binary:
    deps:
      - proto
    cmds:
      - go build -o abyss ./cmd/abyss
  build:
    deps:
      - build-docker
      - build-binary
  site:
    dir: site
    cmds:
      - npm install
      - npm run dev
  puml:
    sources:
      - "**/*.puml"
    cmds:
      - ./scripts/build-diagrams.sh
  build-docker:
    cmds:
      - ./scripts/build-push-docker.sh
  todo:
    cmds:
      - rg 'TODO'
  lint:
    cmds:
      - golangci-lint run
  proto:
    cmds:
      - protoc -I=./schema/proto --go_out=./internal/websockets ./schema/proto/abyss.proto
