# https://taskfile.dev

version: "3"

tasks:
  test:
    cmds:
      - go test ./...
  build-docker:
    cmds:
      - docker build -t abyss:latest .
  build-binary:
    cmds:
      - go build -o abyss ./cmd/abyss
  build:
    deps:
      - build-docker
      - build-binary
  site:
    dir: site
    cmds:
      - npm install
      - npm run dev
  puml:
    sources:
      - "**/*.puml"
    cmds:
      - ./scripts/build-diagrams.sh
  build-docker-base:
    cmds:
      - docker buildx build -f ./build/docker/base/Dockerfile .
