# https://taskfile.dev

version: "3"

tasks:
  build:
    deps:
      - build-docker
      - binary:build
  site:
    dir: site
    deps:
      - puml
    cmds:
      - npm install
      - npm run dev
  puml:
    sources:
      - "**/*.puml"
    cmds:
      - ./scripts/build-diagrams.sh
  build-docker:
    cmds:
      - ./scripts/build-push-docker.sh
  todo:
    cmds:
      - rg 'TODO'
  install-hooks:
    cmds:
      - cp scripts/git-hooks/* .git/hooks/
      - chmod +x .git/hooks/*

includes:
  binary:
    taskfile: ./build/taskfiles/binary.yaml
