// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: abyss.proto

package protobyss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        int32                  `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ResponseFor   string                 `protobuf:"bytes,3,opt,name=response_for,json=responseFor,proto3" json:"response_for,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_abyss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_abyss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_abyss_proto_rawDescGZIP(), []int{0}
}

func (x *Container) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Container) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Container) GetResponseFor() string {
	if x != nil {
		return x.ResponseFor
	}
	return ""
}

func (x *Container) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_abyss_proto protoreflect.FileDescriptor

const file_abyss_proto_rawDesc = "" +
	"\n" +
	"\vabyss.proto\x12\tprotobyss\"\x80\x01\n" +
	"\tContainer\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\x05R\x06typeId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12!\n" +
	"\fresponse_for\x18\x03 \x01(\tR\vresponseFor\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontentB\rZ\v./protobyssb\x06proto3"

var (
	file_abyss_proto_rawDescOnce sync.Once
	file_abyss_proto_rawDescData []byte
)

func file_abyss_proto_rawDescGZIP() []byte {
	file_abyss_proto_rawDescOnce.Do(func() {
		file_abyss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abyss_proto_rawDesc), len(file_abyss_proto_rawDesc)))
	})
	return file_abyss_proto_rawDescData
}

var file_abyss_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_abyss_proto_goTypes = []any{
	(*Container)(nil), // 0: protobyss.Container
}
var file_abyss_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_abyss_proto_init() }
func file_abyss_proto_init() {
	if File_abyss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abyss_proto_rawDesc), len(file_abyss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abyss_proto_goTypes,
		DependencyIndexes: file_abyss_proto_depIdxs,
		MessageInfos:      file_abyss_proto_msgTypes,
	}.Build()
	File_abyss_proto = out.File
	file_abyss_proto_goTypes = nil
	file_abyss_proto_depIdxs = nil
}
