//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin 0.9.0
// 	protoc               v7.36.1
// source: abyss.proto

package protobyss

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const ACPPluginPluginAPIVersion = 1

//go:wasmexport acp_plugin_api_version
func _acp_plugin_api_version() uint64 {
	return ACPPluginPluginAPIVersion
}

var aCPPlugin ACPPlugin

func RegisterACPPlugin(p ACPPlugin) {
	aCPPlugin = p
}

//go:wasmexport acp_plugin_handle_stream
func _acp_plugin_handle_stream(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(ACPContainer)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := aCPPlugin.HandleStream(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
