// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin 0.9.0
// 	protoc               v7.36.1
// source: abyss.proto

package protobyss

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACPContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeId      int32  `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	MessageId   string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ResponseFor string `protobuf:"bytes,3,opt,name=response_for,json=responseFor,proto3" json:"response_for,omitempty"`
	Content     []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ACPContainer) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ACPContainer) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *ACPContainer) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ACPContainer) GetResponseFor() string {
	if x != nil {
		return x.ResponseFor
	}
	return ""
}

func (x *ACPContainer) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// go:plugin type=plugin version=1
type ACPPlugin interface {
	HandleStream(context.Context, *ACPContainer) (*ACPContainer, error)
}
