// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: abyss.proto

package protobyss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACPContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        int32                  `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ResponseFor   string                 `protobuf:"bytes,3,opt,name=response_for,json=responseFor,proto3" json:"response_for,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACPContainer) Reset() {
	*x = ACPContainer{}
	mi := &file_abyss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACPContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACPContainer) ProtoMessage() {}

func (x *ACPContainer) ProtoReflect() protoreflect.Message {
	mi := &file_abyss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACPContainer.ProtoReflect.Descriptor instead.
func (*ACPContainer) Descriptor() ([]byte, []int) {
	return file_abyss_proto_rawDescGZIP(), []int{0}
}

func (x *ACPContainer) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *ACPContainer) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ACPContainer) GetResponseFor() string {
	if x != nil {
		return x.ResponseFor
	}
	return ""
}

func (x *ACPContainer) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ACPContainerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ACPContainer        `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACPContainerList) Reset() {
	*x = ACPContainerList{}
	mi := &file_abyss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACPContainerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACPContainerList) ProtoMessage() {}

func (x *ACPContainerList) ProtoReflect() protoreflect.Message {
	mi := &file_abyss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACPContainerList.ProtoReflect.Descriptor instead.
func (*ACPContainerList) Descriptor() ([]byte, []int) {
	return file_abyss_proto_rawDescGZIP(), []int{1}
}

func (x *ACPContainerList) GetContainers() []*ACPContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

var File_abyss_proto protoreflect.FileDescriptor

const file_abyss_proto_rawDesc = "" +
	"\n" +
	"\vabyss.proto\x12\tprotobyss\"\x83\x01\n" +
	"\fACPContainer\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\x05R\x06typeId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12!\n" +
	"\fresponse_for\x18\x03 \x01(\tR\vresponseFor\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"K\n" +
	"\x10ACPContainerList\x127\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x17.protobyss.ACPContainerR\n" +
	"containers2R\n" +
	"\tACPPlugin\x12E\n" +
	"\rHandleMessage\x12\x17.protobyss.ACPContainer\x1a\x1b.protobyss.ACPContainerListB\rZ\v./protobyssb\x06proto3"

var (
	file_abyss_proto_rawDescOnce sync.Once
	file_abyss_proto_rawDescData []byte
)

func file_abyss_proto_rawDescGZIP() []byte {
	file_abyss_proto_rawDescOnce.Do(func() {
		file_abyss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abyss_proto_rawDesc), len(file_abyss_proto_rawDesc)))
	})
	return file_abyss_proto_rawDescData
}

var file_abyss_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_abyss_proto_goTypes = []any{
	(*ACPContainer)(nil),     // 0: protobyss.ACPContainer
	(*ACPContainerList)(nil), // 1: protobyss.ACPContainerList
}
var file_abyss_proto_depIdxs = []int32{
	0, // 0: protobyss.ACPContainerList.containers:type_name -> protobyss.ACPContainer
	0, // 1: protobyss.ACPPlugin.HandleMessage:input_type -> protobyss.ACPContainer
	1, // 2: protobyss.ACPPlugin.HandleMessage:output_type -> protobyss.ACPContainerList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_abyss_proto_init() }
func file_abyss_proto_init() {
	if File_abyss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abyss_proto_rawDesc), len(file_abyss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_abyss_proto_goTypes,
		DependencyIndexes: file_abyss_proto_depIdxs,
		MessageInfos:      file_abyss_proto_msgTypes,
	}.Build()
	File_abyss_proto = out.File
	file_abyss_proto_goTypes = nil
	file_abyss_proto_depIdxs = nil
}
