// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin 0.9.0
// 	protoc               v7.36.1
// source: abyss.proto

package protobyss

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// go:plugin type=plugin
type ACPPlugin interface {
	HandleMessage(context.Context, *ACPContainer) (*ACPContainerList, error)
}

// go:plugin type=host
type Logging interface {
	// Debug log
	Debug(context.Context, *LogMessage) (*emptypb.Empty, error)
	// Info log
	Info(context.Context, *LogMessage) (*emptypb.Empty, error)
	// Warn log
	Warn(context.Context, *LogMessage) (*emptypb.Empty, error)
	// Error log
	Error(context.Context, *LogMessage) (*emptypb.Empty, error)
}
