// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: abyss.proto

package protobyss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACPContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        int32                  `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ResponseFor   string                 `protobuf:"bytes,3,opt,name=response_for,json=responseFor,proto3" json:"response_for,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACPContainer) Reset() {
	*x = ACPContainer{}
	mi := &file_abyss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACPContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACPContainer) ProtoMessage() {}

func (x *ACPContainer) ProtoReflect() protoreflect.Message {
	mi := &file_abyss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACPContainer.ProtoReflect.Descriptor instead.
func (*ACPContainer) Descriptor() ([]byte, []int) {
	return file_abyss_proto_rawDescGZIP(), []int{0}
}

func (x *ACPContainer) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *ACPContainer) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ACPContainer) GetResponseFor() string {
	if x != nil {
		return x.ResponseFor
	}
	return ""
}

func (x *ACPContainer) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ACPContainerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ACPContainer        `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACPContainerList) Reset() {
	*x = ACPContainerList{}
	mi := &file_abyss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACPContainerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACPContainerList) ProtoMessage() {}

func (x *ACPContainerList) ProtoReflect() protoreflect.Message {
	mi := &file_abyss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACPContainerList.ProtoReflect.Descriptor instead.
func (*ACPContainerList) Descriptor() ([]byte, []int) {
	return file_abyss_proto_rawDescGZIP(), []int{1}
}

func (x *ACPContainerList) GetContainers() []*ACPContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_abyss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_abyss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_abyss_proto_rawDescGZIP(), []int{2}
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogMessage) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_abyss_proto protoreflect.FileDescriptor

const file_abyss_proto_rawDesc = "" +
	"\n" +
	"\vabyss.proto\x12\tprotobyss\x1a\x1bgoogle/protobuf/empty.proto\"\x83\x01\n" +
	"\fACPContainer\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\x05R\x06typeId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12!\n" +
	"\fresponse_for\x18\x03 \x01(\tR\vresponseFor\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"K\n" +
	"\x10ACPContainerList\x127\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x17.protobyss.ACPContainerR\n" +
	"containers\"\x9c\x01\n" +
	"\n" +
	"LogMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\x06fields\x18\x02 \x03(\v2!.protobyss.LogMessage.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012R\n" +
	"\tACPPlugin\x12E\n" +
	"\rHandleMessage\x12\x17.protobyss.ACPContainer\x1a\x1b.protobyss.ACPContainerList2\xef\x01\n" +
	"\aLogging\x128\n" +
	"\x05Debug\x12\x15.protobyss.LogMessage\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\x04Info\x12\x15.protobyss.LogMessage\x1a\x16.google.protobuf.Empty\"\x00\x127\n" +
	"\x04Warn\x12\x15.protobyss.LogMessage\x1a\x16.google.protobuf.Empty\"\x00\x128\n" +
	"\x05Error\x12\x15.protobyss.LogMessage\x1a\x16.google.protobuf.Empty\"\x00B\rZ\v./protobyssb\x06proto3"

var (
	file_abyss_proto_rawDescOnce sync.Once
	file_abyss_proto_rawDescData []byte
)

func file_abyss_proto_rawDescGZIP() []byte {
	file_abyss_proto_rawDescOnce.Do(func() {
		file_abyss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abyss_proto_rawDesc), len(file_abyss_proto_rawDesc)))
	})
	return file_abyss_proto_rawDescData
}

var file_abyss_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_abyss_proto_goTypes = []any{
	(*ACPContainer)(nil),     // 0: protobyss.ACPContainer
	(*ACPContainerList)(nil), // 1: protobyss.ACPContainerList
	(*LogMessage)(nil),       // 2: protobyss.LogMessage
	nil,                      // 3: protobyss.LogMessage.FieldsEntry
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_abyss_proto_depIdxs = []int32{
	0, // 0: protobyss.ACPContainerList.containers:type_name -> protobyss.ACPContainer
	3, // 1: protobyss.LogMessage.fields:type_name -> protobyss.LogMessage.FieldsEntry
	0, // 2: protobyss.ACPPlugin.HandleMessage:input_type -> protobyss.ACPContainer
	2, // 3: protobyss.Logging.Debug:input_type -> protobyss.LogMessage
	2, // 4: protobyss.Logging.Info:input_type -> protobyss.LogMessage
	2, // 5: protobyss.Logging.Warn:input_type -> protobyss.LogMessage
	2, // 6: protobyss.Logging.Error:input_type -> protobyss.LogMessage
	1, // 7: protobyss.ACPPlugin.HandleMessage:output_type -> protobyss.ACPContainerList
	4, // 8: protobyss.Logging.Debug:output_type -> google.protobuf.Empty
	4, // 9: protobyss.Logging.Info:output_type -> google.protobuf.Empty
	4, // 10: protobyss.Logging.Warn:output_type -> google.protobuf.Empty
	4, // 11: protobyss.Logging.Error:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_abyss_proto_init() }
func file_abyss_proto_init() {
	if File_abyss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abyss_proto_rawDesc), len(file_abyss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_abyss_proto_goTypes,
		DependencyIndexes: file_abyss_proto_depIdxs,
		MessageInfos:      file_abyss_proto_msgTypes,
	}.Build()
	File_abyss_proto = out.File
	file_abyss_proto_goTypes = nil
	file_abyss_proto_depIdxs = nil
}
