syntax = "proto3";

package protobyss;

import "google/protobuf/empty.proto";

option go_package = "./protobyss";

message ACPContainer {
  int32 type_id = 1;
  string message_id = 2;
  string response_for = 3;
  bytes content = 4;
}

message ACPContainerList {
  repeated ACPContainer containers = 1;
}

// go:plugin type=plugin
service ACPPlugin {
  rpc HandleMessage(ACPContainer) returns (ACPContainerList);
}

message LogMessage {
    string message = 1;
    map<string, string> fields = 2;
}

// go:plugin type=host
service Logging {
  // Debug log
  rpc Debug(LogMessage) returns (google.protobuf.Empty) {}
  // Info log
  rpc Info(LogMessage) returns (google.protobuf.Empty) {}
  // Warn log
  rpc Warn(LogMessage) returns (google.protobuf.Empty) {}
  // Error log
  rpc Error(LogMessage) returns (google.protobuf.Empty) {}
}
